CREATE TABLE USERS(
                    ID INT GENERATED BY DEFAULT AS IDENTITY,
                    LOGIN NVARCHAR2(50) UNIQUE,
                    PASSWORD NVARCHAR2(255) NOT NULL,
                    EMAIL NVARCHAR2(50) UNIQUE,
                    PRIMARY KEY(ID));



select * from USERS;
drop TABLE USERS;

