--EXCEPTION
CREATE OR REPLACE PACKAGE EXCEPTIONS IS
 --Registration
  EMAIL_ALREADY_EXISTS EXCEPTION;
  LOGIN_ALREADY_EXISTS EXCEPTION;
  INCORRECTLY_EMAIL EXCEPTION;
--Login
NO_SUCH_USER EXCEPTION;


END;