GRANT DBA TO admin;  -- DBA - это роль, предоставляющая максимальные привилегии
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO admin;
COMMIT;
--Profile
CREATE PROFILE ADMIN_PROFILE LIMIT
    PASSWORD_LIFE_TIME 260
    SESSIONS_PER_USER 5
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LOCK_TIME 60
    CONNECT_TIME 720;

--Role
CREATE ROLE ADMIN_ROLE;

GRANT CONNECT TO ADMIN_ROLE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ADMIN_ROLE;
GRANT DBA TO ADMIN_ROLE;
GRANT EXECUTE ON DBMS_OUTPUT TO ADMIN_ROLE; --для вывода сообщений при тесте

GRANT ADMIN_ROLE TO admin;


--user
Drop USER admin;

ALTER USER admin IDENTIFIED BY 1
PROFILE ADMIN_PROFILE;




GRANT EXECUTE ON DBMS_OUTPUT TO admin;
