SET serveroutput ON;

--1.Список преподов на кафедре зад.кодом
CREATE OR REPLACE PROCEDURE PGET_TEACHERS (PCODE TEACHER.PULPIT%TYPE) IS
  CURSOR my_curs IS SELECT TEACHER_NAME, TEACHER FROM TEACHER WHERE PULPIT = PCODE;
  t_name TEACHER.TEACHER_NAME%type;
  t_code TEACHER.TEACHER%type;
BEGIN
  OPEN my_curs;
  LOOP
    DBMS_OUTPUT.PUT_LINE(t_code||' '||t_name);
    FETCH my_curs INTO t_name, t_code;
    EXIT WHEN my_curs%notfound;
  END LOOP;
  CLOSE my_curs;
END;


BEGIN
    PGET_TEACHERS('ИСиТ');
END;



--2. Кол-во преподов на кафедре, зад. в парам
CREATE OR REPLACE FUNCTION FGET_NUM_TEACHERS(PCODE TEACHER.PULPIT%TYPE)
  RETURN NUMBER IS
    tCount NUMBER;
BEGIN
  SELECT COUNT(*) INTO tCount FROM TEACHER WHERE PULPIT = PCODE;
  RETURN tCount;
END;


BEGIN
  DBMS_OUTPUT.PUT_LINE(FGET_NUM_TEACHERS('ИСиТ'));
END;



--3. Список преподов на факультете
CREATE OR REPLACE PROCEDURE PGET_TEACHERS(FCODE FACULTY.FACULTY%TYPE) IS
  CURSOR my_curs IS
    SELECT T.TEACHER_NAME, T.TEACHER, P.FACULTY
    FROM TEACHER T
    INNER JOIN PULPIT P
    ON T.PULPIT = P.PULPIT
    WHERE P.FACULTY = FCODE;
  t_name TEACHER.TEACHER_NAME%type;
  t_code TEACHER.TEACHER%type;
  t_faculty PULPIT.FACULTY%type;
BEGIN
  OPEN my_curs;
  LOOP
    DBMS_OUTPUT.PUT_LINE(t_name||' '||t_code||' '||t_faculty);
    FETCH my_curs INTO t_name, t_code, t_faculty;
    EXIT WHEN my_curs%notfound;
  END LOOP;
  CLOSE my_curs;
END;

BEGIN
    PGET_TEACHERS('ИДиП');
END;


-- Список дисциплин на кафедре
CREATE OR REPLACE PROCEDURE PGET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) IS
  CURSOR my_curs IS
      SELECT SUBJECT, SUBJECT_NAME, S.PULPIT
        FROM SUBJECT S
        WHERE S.PULPIT = PCODE;
  s_subject SUBJECT.SUBJECT%TYPE;
  s_subject_name SUBJECT.SUBJECT_NAME%TYPE;
  s_pulpit SUBJECT.PULPIT%TYPE;
BEGIN
  OPEN my_curs;
  LOOP
    DBMS_OUTPUT.PUT_LINE(s_subject||' '||s_subject_name||' '||s_pulpit);
    FETCH my_curs INTO s_subject, s_subject_name, s_pulpit;
    EXIT WHEN my_curs%notfound;
  END LOOP;
  CLOSE my_curs;
END;


BEGIN
  PGET_SUBJECTS('ИСиТ');
END;



--5. Кол-во преподов на факультете
CREATE OR REPLACE FUNCTION FGET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE)
  RETURN NUMBER IS
    tCount NUMBER;
BEGIN
  SELECT COUNT(*) INTO tCount FROM TEACHER T
  INNER JOIN PULPIT P
  ON T.PULPIT = P.PULPIT
  WHERE P.FACULTY = FCODE;
    RETURN tCount;
END;


BEGIN
  DBMS_OUTPUT.PUT_LINE(FGET_NUM_TEACHERS('ИДиП'));
END;



--Кол-во дисциплин на кафедре
CREATE OR REPLACE FUNCTION FGET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE)
  RETURN NUMBER IS
    tCount NUMBER:=0;
BEGIN
    SELECT COUNT(*) INTO tCount
      FROM SUBJECT
      WHERE SUBJECT.PULPIT = PCODE;
    RETURN tCount;
END;

BEGIN
  DBMS_OUTPUT.PUT_LINE(FGET_NUM_SUBJECTS('ИСиТ'));
END;



--6. Пакет, сод. процедуры и ф-ции
CREATE OR REPLACE PACKAGE TEACHERS AS
    FCODE FACULTY.FACULTY%TYPE;
    PCODE SUBJECT.PULPIT%TYPE;
    PROCEDURE PGET_TEACHERS(FCODE FACULTY.FACULTY%TYPE);
    PROCEDURE PGET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE);
    FUNCTION FGET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
    FUNCTION FGET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END TEACHERS;


CREATE OR REPLACE PACKAGE BODY TEACHERS AS
  FUNCTION FGET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER
    IS tCount NUMBER;
        BEGIN
      SELECT COUNT(*) INTO tCount FROM TEACHER T
      INNER JOIN PULPIT P
      ON T.PULPIT = P.PULPIT
      WHERE P.FACULTY = FCODE;
        RETURN tCount;
      END FGET_NUM_TEACHERS;
  FUNCTION FGET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE)
      RETURN NUMBER IS
        tCount NUMBER:=0;
    BEGIN
        SELECT COUNT(*) INTO tCount
          FROM SUBJECT
          WHERE SUBJECT.PULPIT = PCODE;
        RETURN tCount;
    END FGET_NUM_SUBJECTS;
    
    
  PROCEDURE PGET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) IS
      CURSOR my_curs IS
          SELECT SUBJECT, SUBJECT_NAME, S.PULPIT
            FROM SUBJECT S
            WHERE S.PULPIT = PCODE;
      s_subject SUBJECT.SUBJECT%TYPE;
      s_subject_name SUBJECT.SUBJECT_NAME%TYPE;
      s_pulpit SUBJECT.PULPIT%TYPE;
    BEGIN
      OPEN my_curs;
      LOOP
        DBMS_OUTPUT.PUT_LINE(s_subject||' '||s_subject_name||' '||s_pulpit);
        FETCH my_curs INTO s_subject, s_subject_name, s_pulpit;
        EXIT WHEN my_curs%notfound;
      END LOOP;
      CLOSE my_curs;
    END PGET_SUBJECTS;
    
    
  PROCEDURE PGET_TEACHERS(FCODE FACULTY.FACULTY%TYPE) IS
      CURSOR my_curs IS
        SELECT T.TEACHER_NAME, T.TEACHER, P.FACULTY
        FROM TEACHER T
        INNER JOIN PULPIT P
        ON T.PULPIT = P.PULPIT
        WHERE P.FACULTY = FCODE;
      t_name TEACHER.TEACHER_NAME%type;
      t_code TEACHER.TEACHER%type;
      t_faculty PULPIT.FACULTY%type;
    BEGIN
      OPEN my_curs;
      LOOP
        DBMS_OUTPUT.PUT_LINE(t_name||' '||t_code||' '||t_faculty);
        FETCH my_curs INTO t_name, t_code, t_faculty;
        EXIT WHEN my_curs%notfound;
      END LOOP;
      CLOSE my_curs;
    END PGET_TEACHERS;
END TEACHERS;
  
  
BEGIN
  DBMS_OUTPUT.PUT_LINE(TEACHERS.FGET_NUM_TEACHERS('ИДиП'));
  DBMS_OUTPUT.PUT_LINE(TEACHERS.FGET_NUM_SUBJECTS('ИСиТ'));
  TEACHERS.PGET_TEACHERS('ИДиП');
  TEACHERS.PGET_SUBJECTS('ИСиТ');
END;











